# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.boffbowsh.co.uk" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Paul Bowsher - Independent Software Contractor
  avatar: avatar.png
  gravatar: ff870982e84d7f6dd6e1af91ab4e3797
  description: "Personal Blog and Portfolio of Paul Bowsher, A Software Contractor in London" # used by search engines

  # Header and footer text
  header_text: >
    <p>Independent Software Contractor in London, currently at Government Digital Service.</p>

    <p>Does Ruby, Python, Node/io.js and DevOps. Happy to learn other stuff for food.</p>

    <p>Specialises in Distributed Systems, scaling things and making graphs go the right way.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: paul.bowsher@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: "boffbowsh"
  google_plus: 
  instagram:
  linkedin: https://uk.linkedin.com/in/paulbowsher
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: http://stackoverflow.com/users/2408455/boffbowsh
  steam:
  tumblr:
  twitter: boffbowsh
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-9394692-1
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
